import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { NavBar } from "@/components/navbar";
import Alert from "@/components/Alert";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div
          className="grid grid-rows-2 grid-cols-1 min-w-full"
          style={{ gridTemplateRows: "minmax(4rem, auto) 1fr" }}
        >
          <NavBar />
          {children}
        </div>
        <Alert />
        <Toaster/>
      </body>
    </html>
  );
}

